/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas_adibah;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;

/**
 *
 * @author ASUS
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLOGIN = new javax.swing.JMenuItem();
        menuLOGOUT = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuEXIT = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jMenu1.setText("LOGIN / MASUK");

        menuLOGIN.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        menuLOGIN.setText("LOGIN");
        menuLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLOGINActionPerformed(evt);
            }
        });
        jMenu1.add(menuLOGIN);

        menuLOGOUT.setText("LOGOUT");
        menuLOGOUT.setEnabled(false);
        menuLOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLOGOUTActionPerformed(evt);
            }
        });
        jMenu1.add(menuLOGOUT);
        jMenu1.add(jSeparator1);

        menuEXIT.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        menuEXIT.setText("EXIT");
        menuEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEXITActionPerformed(evt);
            }
        });
        jMenu1.add(menuEXIT);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEXITActionPerformed
        int pilih = JOptionPane.showConfirmDialog(null,"keluar aplikasi",
                "konfirmasi",JOptionPane.OK_CANCEL_OPTION);
        if(pilih ==JOptionPane.OK_OPTION){
            System.exit(0);
        }else {
            JOptionPane.getRootFrame();
        
    }
        
        
    }//GEN-LAST:event_menuEXITActionPerformed

    private void menuLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLOGINActionPerformed
        desktopPane.removeAll();
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        desktopPane.add(loginForm);
        menuLOGIN.setEnabled(false);
        menuLOGOUT.setEnabled(true);
    }//GEN-LAST:event_menuLOGINActionPerformed

    private void menuLOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLOGOUTActionPerformed
        desktopPane.removeAll();
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        desktopPane.add(loginForm);
        menuLOGOUT.setEnabled(false);
        menuLOGIN.setEnabled(true);
    }//GEN-LAST:event_menuLOGOUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuEXIT;
    private javax.swing.JMenuItem menuLOGIN;
    private javax.swing.JMenuItem menuLOGOUT;
    // End of variables declaration//GEN-END:variables
}
